/*
 * generated by Xtext 2.38.0
 */
package fr.n7.serializer;

import com.google.inject.Inject;
import fr.n7.services.PDL1GrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class PDL1SyntacticSequencer extends AbstractSyntacticSequencer {

	protected PDL1GrammarAccess grammarAccess;
	protected AbstractElementAlias match_WorkDefinition___LeftCurlyBracketKeyword_2_0___UseRessourcesKeyword_2_1_0_ColonKeyword_2_1_1__q_RightCurlyBracketKeyword_2_2__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (PDL1GrammarAccess) access;
		match_WorkDefinition___LeftCurlyBracketKeyword_2_0___UseRessourcesKeyword_2_1_0_ColonKeyword_2_1_1__q_RightCurlyBracketKeyword_2_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getWorkDefinitionAccess().getLeftCurlyBracketKeyword_2_0()), new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getWorkDefinitionAccess().getUseRessourcesKeyword_2_1_0()), new TokenAlias(false, false, grammarAccess.getWorkDefinitionAccess().getColonKeyword_2_1_1())), new TokenAlias(false, false, grammarAccess.getWorkDefinitionAccess().getRightCurlyBracketKeyword_2_2()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_WorkDefinition___LeftCurlyBracketKeyword_2_0___UseRessourcesKeyword_2_1_0_ColonKeyword_2_1_1__q_RightCurlyBracketKeyword_2_2__q.equals(syntax))
				emit_WorkDefinition___LeftCurlyBracketKeyword_2_0___UseRessourcesKeyword_2_1_0_ColonKeyword_2_1_1__q_RightCurlyBracketKeyword_2_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('{' ('useRessources' ':')? '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_WorkDefinition___LeftCurlyBracketKeyword_2_0___UseRessourcesKeyword_2_1_0_ColonKeyword_2_1_1__q_RightCurlyBracketKeyword_2_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
